apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.secret.tls.crt | b64enc | quote }}
  tls.key: {{ .Values.secret.tls.key | b64enc | quote }}
