apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-secret
  namespace: {{ .Values.mapconfig.namespace }}
type: Opaque
data:
  POSTGRES_USER: {{ .Values.postgres.POSTGRES_USER | b64enc }}
  POSTGRES_PASSWORD: {{ .Values.postgres.POSTGRES_PASSWORD | b64enc }}