apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  namespace: {{ .Values.mapconfig.namespace }}
type: Opaque
data:
  TEST_PASSWORD: {{ .Values.secret.data.TEST_PASSWORD | b64enc }}
  TEST_TOKEN: {{ .Values.secret.data.TEST_TOKEN | b64enc }}
  POSTGRES_HOST: {{ .Values.secret.postgres.POSTGRES_HOST | b64enc }}
  POSTGRES_DB: {{ .Values.secret.postgres.POSTGRES_DB | b64enc }}
  POSTGRES_PASSWORD: {{ .Values.secret.postgres.POSTGRES_PASSWORD | b64enc }}
  POSTGRES_USER: {{ .Values.secret.postgres.POSTGRES_USER | b64enc }}
