apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
  namespace: {{ .Values.mapconfig.namespace }}
data:
  REDIS_HOST: "{{ .Values.redis.REDIS_HOST }}"
  REDIS_PORT: "{{ .Values.redis.REDIS_PORT }}"
  APP_PORT: "{{ .Values.app.APP_PORT }}"
