apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  namespace: {{ .Values.mapconfig.namespace }}
type: Opaque
data:
  TEST_PASSWORD: {{ .Values.secret.data.TEST_PASSWORD | b64enc }}
  TEST_TOKEN: {{ .Values.secret.data.TEST_TOKEN | b64enc }}