apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  namespace: {{ .Values.mapconfig.namespace }}
type: Opaque
data:
  password: {{ .Values.secret.password | b64enc }}
  token: {{ .Values.secret.token | b64enc }}